[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.localnet]
yona = "yonaMBw7KLYvQSspboB2GGAt5EsQqV28dZZasKhKGqC"

[programs.devnet]
yona = "yonaMBw7KLYvQSspboB2GGAt5EsQqV28dZZasKhKGqC"

[programs.mainnet]
yona = "yonaMBw7KLYvQSspboB2GGAt5EsQqV28dZZasKhKGqC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/light.ts"

[package]
name = "yona"
version = "0.1.0"
description = "yona program"
repository = "https://github.com/Yona-Labs/yona-privacy-app"


[[test.genesis]]
address = "CarrotwivhMpDnm27EHmRLeQ683Z1PufuqEmBZvD282s"
program = "./carrot.so"

# carrot log
[[test.genesis]]
address = "7Mc3vSdRWoThArpni6t5W4XjvQf4BuMny1uC8b6VBn48"
program = "./carrot-log.so"